name: Build & push to AWS ECR

on:
  push:
    branches: [main]

jobs:
  Build-and-push:
    runs-on: windows-latest

    steps:
    -  name: checkout code
       uses: actions/checkout@v2

    -  name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1

    -  name: login to aws ecr
       id: ecr-login
       uses: aws-actions/amazon-ecr-login@v1

    - id: docker-tag
      uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

    - name: Build docker image
      id: docker-build
      env:
        ECR-REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR-REPOSITORY: docker-image-repository
        IMAGE_TAG: ${{ steps.docker-tag.outputs.tag }}
      run: |
          echo $ECR-REGISTRY
          echo $ECR-REPOSITORY
          docker build -t $ECR-REGISTRY/$ECR-REPOSITORY:$IMAGE_TAG .
          docker push $ECR-REGISTRY/$ECR-REPOSITORY:$IMAGE_TAG

        


       
    
  
